### ISSUE TITLE
Prepare rucio.cfg and client inside cluster for testing and debugging

### ISSUE THREAD

**Issue by goseind** [cern-vre/cern-vre#25]
In order to allow for easy debugging, a client container should be running in the cluster:
Also, it is possible to use the rucio cli from within CERN and use env var or `rucio.cfg`.

Infos and examples:

- https://github.com/rucio/rucio/blob/master/etc/rucio.cfg.template
- https://github.com/rucio/containers/tree/master/clients#getting-started

**Comment by goseind** [comment]
With the provided `rucio.cfg` file, the output should look like this:
```bash
rucio whoami
account_type : SERVICE
suspended_at : None
created_at : 2023-01-23T15:51:44
account    : root
status     : ACTIVE
email      : None
deleted_at : None
updated_at : 2023-01-23T15:51:44
```

**Comment by egazzarr** [comment]
Done, passwords stored in the `root-account` secret and the 'rucio-client' pod (via `adm/rucio-clients.yaml`) executes a container that generates the config for the new server and the root account.

**Comment by egazzarr** [comment]
The client is active. This is done before working on IAM sync, so in the future we could envision having it connected to the ESCAPE service account.
